[package]
name = "structures"
version = "0.1.0"
authors = ["Sergio Ben√≠tez <sergio.benitez@getbuilt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
